In [1]:
!pip install tensorflow

  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4847 sha256=cb591904fa354c72c73e0ccb39139ca3f1d87f204a9801ddd7baa494d25a7c0c
  Stored in directory: c:\users\ridwo\appdata\local\pip\cache\wheels\b6\0d\90\0d1bbd99855f99cb2f6c2e5ff96f8023fad8ec367695f7d72d
Successfully built termcolor
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.1
    Uninstalling protobuf-3.20.1:
      Successfully uninstalled protobuf-3.20.1


In [2]:
#Importing necessary Libraries
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [3]:
#Loading Dataset
data = pd.read_csv("Churn_Modelling.csv")

In [4]:
print(data)

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMemb

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [6]:
#Generating Matrix of Features
X = data.iloc[:,3:13].values

In [7]:
#Generating Dependent Variable Vectors
Y = data.iloc[:,13].values

In [8]:
#Encoding Categorical Variable Gender
from sklearn.preprocessing import LabelEncoder
LE1 = LabelEncoder()
X[:,2] = np.array(LE1.fit_transform(X[:,2]))

In [9]:
#Encoding Categorical variable Geography
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct =ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder="passthrough")
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [11]:
#Splitting dataset into training and testing dataset
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [12]:
#Performing Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
#Initialising ANN
#ann = tf.keras.models.Sequential()
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
ann=keras.Sequential()

In [14]:
ann.add(Dense(units=10,activation="relu"))

In [15]:
#Adding First Hidden Layer
ann.add(Dense(units=6,activation="relu"))

In [16]:
#Adding Second Hidden Layer
ann.add(Dense(units=6,activation="relu"))

In [17]:
#Adding Output Layer
ann.add(Dense(units=1,activation="sigmoid"))

In [18]:
#Compiling ANN
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

In [19]:
#Fitting ANN
ann.fit(X_train,Y_train,batch_size=32,epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5596 - accuracy: 0.7442
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4547 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4305 - accuracy: 0.8021
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4146 - accuracy: 0.8180
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3984 - accuracy: 0.8307
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3800 - accuracy: 0.8429
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3660 - accuracy: 0.8508
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3586 - accuracy: 0.8534
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3536 - accuracy: 0.8560
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3507 - accura

250/250 [==============================] - 1s 3ms/step - loss: 0.3255 - accuracy: 0.8676
Epoch 82/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3254 - accuracy: 0.8658
Epoch 83/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3253 - accuracy: 0.8654
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3252 - accuracy: 0.8654
Epoch 85/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3250 - accuracy: 0.8652
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3249 - accuracy: 0.8655
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3248 - accuracy: 0.8656
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3247 - accuracy: 0.8660
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3248 - accuracy: 0.8650
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3237 - accuracy: 

In [20]:
y_pred=ann.predict(X_test)

63/63 [==============================] - 1s 3ms/step


In [21]:
y_pred=(y_pred>=0.5)

In [22]:
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [23]:
from sklearn.metrics import confusion_matrix
cf=confusion_matrix(Y_test,y_pred)

In [24]:
print(cf)

[[1512   83]
 [ 196  209]]


In [25]:
from sklearn.metrics import accuracy_score
score=accuracy_score(Y_test,y_pred)
print(score)

0.8605


In [26]:
ann.get_weights()

[array([[ 1.91610932e-01,  1.00531422e-01,  1.88610524e-01,
         -3.64878207e-01, -1.63751081e-01, -3.97570103e-01,
          2.57939994e-01,  4.68126684e-02,  1.32175118e-01,
         -4.80804360e-03],
        [ 4.05270934e-01,  2.06483305e-01,  5.93963750e-02,
          3.73436421e-01, -4.56075728e-01,  2.02162657e-02,
         -2.52378225e-01, -6.69760525e-01,  3.63308966e-01,
         -2.56989360e-01],
        [ 1.36166841e-01,  3.63097996e-01,  1.17894329e-01,
         -3.07397783e-01,  1.01480044e-01, -6.30654812e-01,
         -3.97728109e-05,  9.40895081e-02,  7.35347569e-02,
          1.22970231e-01],
        [ 7.52361044e-02,  2.62688935e-01,  1.28394246e-01,
          6.87552989e-02,  1.38839126e-01, -1.31335109e-01,
         -1.76907293e-02, -1.86214730e-01,  2.86658913e-01,
         -2.17000335e-01],
        [-4.00859267e-02,  1.14664778e-01,  2.32151132e-02,
         -8.41580797e-03,  1.17369778e-01,  3.23788188e-02,
          2.26223230e-01, -3.30025375e-01, -3.363653